export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_LEARNING_MODE = "SET_LEARNING_MODE";

export const FETCH_DOGS_REQUEST = "FETCH_DOGS_REQUEST";
export const FETCH_DOGS_SUCCESS = "FETCH_DOGS_SUCCESS";
export const FETCH_DOGS_FAILURE = "FETCH_DOGS_FAILURE";
export const IS_DOG_UPLOADED = "IS_DOG_UPLOADED";

export const SET_USER_DOGGYDEX = "SET_USER_DOGGYDEX";
export const CLEAR_USER_DOGGYDEX = "CLEAR_USER_DOGGYDEX";
